### ISSUE TITLE
about checkpoint

### ISSUE THREAD

**Issue by Hrren** [sgvaze/osr_closed_set_all_you_need#11]
Thanks for your wonderful work

I want to know why the checkpoint is not saved when I only use the CEloss, I read the code but did not find where should be modify.

**Comment by sgvaze** [comment]
Hello, sorry for the late reply and thanks for your interest in our work!

Yes, I do need to clean this up at some point (the saving is a legacy from the ARPL code). However, all models should be saved with path format: 

`/work/sagar/open_set_recognition/methods/ARPL/log/{EXP_ID}/arpl_models/{DATASET}/checkpoints/{DATASET}_{EPOCH}_{LOSS}.pth`

Also, 'CELoss' is known as 'Softmax' in this code. Let me know if this helps!

**Comment by Hrren** [comment]
hello, thanks for your reply
but when I check the saved checkpoint, The file size is only 3.9M, why is this happening?

**Comment by Hrren** [comment]
hello, thanks for your reply
but when I check the saved checkpoint, The file size is only 3.9M, why is this happening?

**Comment by sgvaze** [comment]
This should be because the model is very small (e.g VGG32, roughly 1M parameters)
