### ISSUE TITLE
Clarification on ImageNet-21K

### ISSUE THREAD

**Issue by zjysteven** [sgvaze/osr_closed_set_all_you_need#12]
Hi,

Thanks for making the code public which helps a lot. I'm wondering if you were using the fall11 version of ImageNet-21K for the open splits. I'm now using the winter21 version and some of the classes in the 'Hard' split do not exist anymore (e.g., 'n10506915').

If this is true, then a problem is that the ImageNet website doesn't seem to host fall11 version anymore (correct me if I'm wrong). If this is the case, then would it be possible for you to update the 'Hard' split based on the available winter21 version?

Thanks

**Comment by zjysteven** [comment]
Also, I was reproducing the CrossEntropy+ results of ResNet50 on ImageNet 'Easy' split. However, I'm getting better results than what's reported in the paper.

|| Acc. | AUROC | OSCR |
|---| --------- | --------- |-----|
|Paper|78.8|78.2|66.1|
|Mine|80.4|81.0|70.3|

I find it weird that the closed-set accuracy is different. Besides the effect of the accuracy, the detection performance difference could also be due to the discrepancy of the ImageNet-21K data though (like I mentioned in the last post, I suppose that you were using fall11 but I'm using winter21 version).

**Comment by sgvaze** [comment]
Hello, sorry for the late reply!

**On the ImageNet classes**: Yes, you are correct that our class splits are based on the `fall11` version which is no longer available. As we only have the `fall11` splits on our server, could you identify which classes are no longer available in the `winter21` version (it should only be about 20 categories)? I will then create a version where these classes are removed from the `Hard` split.

**On the accuracy of the R50**: The models in `timm` are constantly evolving. When we evaluated a model whose accuracy was 78.8. The R50 in the latest `timm` version looks to be stronger.

**Comment by zjysteven** [comment]
@sgvaze Thanks for the clarification. I can make a list of the classes that do not exist in winter21. Will update this thread once I finish.

**Comment by zjysteven** [comment]
@sgvaze The missing wnids of Hard split in ImageNet-21K-P (winter21 version) are:
```python
['n10506915', 'n10498986', 'n09941787', 'n10562283', 'n09911226', 
 'n10645017', 'n10263790', 'n10510245', 'n10259997', 'n10079399', 
 'n10624437', 'n09943239', 'n10093475', 'n09770359', 'n10134178', 
 'n10313239', 'n10259348', 'n10296176', 'n10259780', 'n10092978']
```

**Comment by sgvaze** [comment]
Perfect, thanks for providing these! Apologies again for the late reply, we are updating the splits for the Winter21 release right now - stay tuned!

**Comment by sgvaze** [comment]
@zjysteven Btw, I re-ran the ImageNet experiment with the latest timm ResNet50 and got the same results as you. I may update these numbers in the ArXiv version.

**Comment by sgvaze** [comment]
Added the new splits [here](https://github.com/sgvaze/osr_closed_set_all_you_need/blob/main/data/open_set_splits/imagenet_osr_splits_winter21.pkl)!
