### ISSUE TITLE
pretrained model don't match

### ISSUE THREAD

**Issue by LP308210365** [sgvaze/osr_closed_set_all_you_need#14]
Thanks for your work

When i train the model with parameters "--model=timm_resnet50_pretrained  --resnet50_pretrain=places", and i download  pretrained model from https://github.com\\nanxuanzhao\\Good_transfer,  i get  the error :"Missing key(s) in state_dict: "conv1.weight", "bn1.weight", "bn1.bias", "bn1.running_mean",.....................".

i think this error causes by mismatched weight and model,  could you please tell me the right method to train model with pretrained weight, or right link to download weight?

**Comment by sgvaze** [comment]
Hi! This is likely an issue with the DataParallel wrapper. Does either the state_dict of the instantiated model object, or of the weights you are loading, have `module.` at the start of the keys? If so, you can use the `strip_state_dict` function in the code.

**Comment by LP308210365** [comment]
Thanks a lot! I will try it later

**Comment by sgvaze** [comment]
Closing for now, feel free to get in touch again if there's still problems
