### ISSUE TITLE
How to predict a single img with label known or unknown?

### ISSUE THREAD

**Issue by LP308210365** [sgvaze/osr_closed_set_all_you_need#15]
Hello again!
I'm working on a task with your code, i have seen that all methods are evaluate by AUROC, a threshold independent metric, but now i need to predict the label by threshold, is there any func in code to do that?

**Comment by LP308210365** [comment]
I found the func to get the threshold:"test/utils/find_nearest"

**Comment by sgvaze** [comment]
Hi! `test.utils.find_nearest.acc_at_t` might be what you're looking for. It computes binary (open-set/closet-set) accuracy at a given threshold. 

The choice of threshold will depend on your downstream application (e.g do you care about false positives or false negatives) and would typically be chosen on some validation examples. We didn't tackle this here! Hope this helps.

**Comment by LP308210365** [comment]
thanks a lot, this is what i want, i train the classifier32 with custom dataset,  i think the given threshold can work in this domain
