### ISSUE TITLE
Question about fine-grained dataset CUB and Aircraft

### ISSUE THREAD

**Issue by Hrren** [sgvaze/osr_closed_set_all_you_need#18]
Hello
When I tried to reproduce the AUC results of the Easy and Medium datasets for the CUB and Aircraft datasets, I couldn't reproduce the results of the paper, for CUB, Easy and Medium were only 87.5 and 81.8; for Aircraft is 89.0 and 85.4.
I trained according to the bash script/osr_finegrained_train.sh and fix corresponding Optimal Hyper-parameters, and used the places_moco pre-trainmodel, but the results in the paper could not be reproduced. What is the reason?

![image](https://user-images.githubusercontent.com/88883209/180220205-947263e1-aa95-4a89-ba6e-633f7ffb1d9b.png)
![image](https://user-images.githubusercontent.com/88883209/180220436-a88129a2-973d-42f8-9729-9d80f005e13f.png)
![image](https://user-images.githubusercontent.com/88883209/180220547-02b9e612-7d9b-4598-94b9-7e98e477f430.png)

**Comment by sgvaze** [comment]
Hi, I imagine the reason for the discrepancy with the 'Medium' examples is that in the latest version, we combine 'Medium' and 'Hard' into a single split. Regarding 'Easy', I am not sure exactly the reason for the discrepancy (we fix the seeds at the start of training), but within 1% AUROC may be expected between different runs.
