### ISSUE TITLE
Running pretrained configuration

### ISSUE THREAD

**Issue by NivC** [sgvaze/osr_closed_set_all_you_need#3]
Hi,

Thanks again for the code.

I tried to run with pretrained weights. Two questions about it please:

1. Do you have any suggested configuration (hyperparameters, etc.) to run with one of the pretrained model?

2. As you suggested in you code, I tried to download a model from:
3. 
https://github.com/nanxuanzhao/Good_transfer

Yet, I got the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cs/labs/peleg/nivc/multimodal_ad/osr_closed_set_all_you_need/methods/ARPL/osr.py", line 354, in <module>
    res = main_worker(options, args)
  File "/cs/labs/peleg/nivc/multimodal_ad/osr_closed_set_all_you_need/methods/ARPL/osr.py", line 153, in main_worker
    net = get_model(args, wrapper_class=wrapper_class)
  File "/cs/labs/peleg/nivc/multimodal_ad/osr_closed_set_all_you_need/models/model_utils.py", line 251, in get_model
    model.load_state_dict(state_dict)
  File "/cs/labs/yedid/nivc/nn_code/envs/fa_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNetABN:
	Missing key(s) in state_dict: "bn1.bns.0.weight", "bn1.bns.0.bias", "bn1.bns.0.running_mean", "bn1.bns.0.running_var", "bn1.bns.1.weight", "bn1.bns.1.bias", "bn1.bns.1.running_mean", "bn1.bns.1.running_var", "layer1.0.bn1.bns.0.weight", "layer1.0.bn1.bns.0.bias", "layer1.0.bn1.bns.0.running_mean", "layer1.0.bn1.bns.0.running_var", "layer1.0.bn1.bns.1.weight", "layer1.0.bn1.bns.1.bias", "layer1.0.bn1.bns.1.running_mean", "layer1.0.bn1.bns.1.running_var", "layer1.0.bn2.bns.0.weight", "layer1.0.bn2.bns.0.bias", "layer1.0.bn2.bns.0.running_mean", "layer1.0.bn2.bns.0.running_var", "layer1.0.bn2.bns.1.weight", "layer1.0.bn2.bns.1.bias", "layer1.0.bn2.bns.1.running_mean", "layer1.0.bn2.bns.1.running_var", "layer1.0.bn3.bns.0.weight", "layer1.0.bn3.bns.0.bias", "layer1.0.bn3.bns.0.running_mean", "layer1.0.bn3.bns.0.running_var", "layer1.0.bn3.bns.1.weight", "layer1.0.bn3.bns.1.bias ...

Could you please advise which model should I download or how to resolve that error?

Niv.

**Comment by sgvaze** [comment]
Hi, sorry for the late reply - we had a deadline. 

Please try running: `bash_scripts/osr_finegrained_train.sh` after downloading the weights and editing `places_moco_path` in `config.py`, this works on our end.
We have also updated the FGVC splits to match the paper in the latest commit: ad43f2a9082f0912da4d501f6a47648910382494

Closing for now!
