### ISSUE TITLE
Random Augment M & N

### ISSUE THREAD

**Issue by deval-mehta** [sgvaze/osr_closed_set_all_you_need#4]
Thanks for this amazing codebase.

I think the M & N for the Random Augment have been interchanged in the README and the code. M should be N and vice-versa.

As in the file data.augmentations.randaugment.py Line 277 Line 278 correspond to the correct setting. Please let me know if this is wrong. May be just update the README to alleviate any confusion.

**Comment by sgvaze** [comment]
Hi, thanks for your interest in our work and apologies for the delayed reply - we had a deadline. 

That's a great spot, thanks! Fixed here: ddea5de7883d3021c6a2e9ca6894196a19660eac
