### ISSUE TITLE
In CIFAR10-OSR, the first and seond splits are the same 

### ISSUE THREAD

**Issue by roomo7time** [sgvaze/osr_closed_set_all_you_need#8]
https://github.com/sgvaze/osr_closed_set_all_you_need/blob/c3fee78818f83052cd8fed7826d5511a5a9d7165/data/open_set_splits/osr_splits.py#L19

Hi, first of all, thank you for sharing  the code.

For the OSR-CIFAR10 experiment, the first and second splits are exactly the same. I am wondering if this is actually correct.

**Comment by sgvaze** [comment]
Hi, these class splits were inherited from a previous paper for fair comparison. But yes, the duplicate is an error. I suggest to keep the splits the same to allow fair comparison with previous literature but to highlight the duplicate in the README.

**Comment by roomo7time** [comment]
Thank you for clarification!
