### ISSUE TITLE
Any plans to include Imagenet?

### ISSUE THREAD

**Issue by agaldran** [sgvaze/osr_closed_set_all_you_need#9]
Hello again,

I have been able to train models for all benchmarks, old and newly proposed, so thanks for that! 

I am just missing the Imagenet experiment, which appears in Table 3 of the paper (with an easy and a hard split). The ImageNet splits seem to be present in `data/open_set_split/imagenet_osr_splits.pkl`, but there is not pytorch dataset that implements them, nor do ImageNet hyperparameters appear in `utils/paper_hyperparameters.csv`. I was wondering if you have any plans to release the ImageNet experimental setup anytime soon? Thanks!!

Also, may I email you with a separate question about your work that does not fit in a github issue? Thank you very much!!

Adrian

**Comment by sgvaze** [comment]
Hi, glad the code is running smoothly! 

Yes, we plan to include the Torch datasets for ImageNet evaluation soon. Regarding hyper-parameters, our benchmarking for Cross-Entropy+ simply took a ResNet-50 pre-trained on ImageNet-1K from the [timm library](https://github.com/rwightman/pytorch-image-models). 

For ARPL+, we fine-tined the ResNet-50 for 10 epochs on ImageNet-1K using standard ImageNet augmentations (Random Crop and Random Flip). We will provide these details when we update the repo.

Finally, of course, please find my email in the paper!

**Comment by agaldran** [comment]
I finally found the time to write you an email! Closing now, thanks!!
